{{- $root := . }}
{{- range .Values.serviceAccounts }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}-role
  labels:
{{ include "eck-resources.labels" $root | indent 4 }}
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
rules:
{{ toYaml .rules }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  labels:
{{ include "eck-resources.labels" $root | indent 4 }}
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}-rb
  labels:
{{ include "eck-resources.labels" $root | indent 4 }}
{{- if .annotations }}
  annotations:
{{ toYaml .annotations | indent 4 }}
{{- end }}
subjects:
- kind: ServiceAccount
  name: {{ .name }}
roleRef:
  kind: Role
  name: {{ .name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
