{{- if .Values.kubeconfigContent }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keess.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "keess.labels" . | nindent 4 }}
data:
  config: {{ .Values.kubeconfigContent | trim | b64enc | quote }}
{{- end }}