{{- if or .Values.bigipCtrlAS3.kubeapi.enabled .Values.bigipCtrlAS3.ingress.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: as3cm
  namespace: {{ $.Release.Namespace }}
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.51.0",
        "label": "http",
        "remark": "{{ .Values.cluster.name }} Template",
        "{{ .Values.cluster.name }}": {
          "class": "Tenant",
          "as3": {
            "class": "Application",
            "template": "generic",
            {{- if .Values.bigipCtrlAS3.kubeapi.enabled }}
            "webdev_{{ .Values.cluster.name }}_kubeapi_{{ .Values.bigipCtrlAS3.kubeapi.vs.port }}_vs": {
              "class": "Service_L4",
              "layer4": "tcp",
              "profileL4": {
                "bigip": "/Common/fastL4"
              },
              "snat": {
                "bigip": "{{ .Values.bigipCtrlAS3.snatPool }}"
              },
              "virtualPort": {{ .Values.bigipCtrlAS3.kubeapi.vs.port }},
              "remark": "{{ .Values.cluster.name }} kubeapi vs",
              "virtualAddresses": [
                "{{ .Values.bigipCtrlAS3.kubeapi.vs.address }}"
              ],
              "pool": "{{ .Values.cluster.name }}_kubeapi_pool"
            },
            "{{ .Values.cluster.name }}_kubeapi_pool": {
              "class": "Pool",
              "monitors": [
                {"bigip": "/Common/https_kubeapi_healthz"}
              ],
              "members": [
                {
                  "servicePort": {{ .Values.bigipCtrlAS3.kubeapi.pool.port }},
                  "serverAddresses": {{ toJson .Values.bigipCtrlAS3.kubeapi.pool.members }}
                }
              ]
            {{- end }}
            {{- if and .Values.bigipCtrlAS3.kubeapi.enabled .Values.bigipCtrlAS3.ingress.enabled }}
            },
            {{- end }}
            {{- if .Values.bigipCtrlAS3.ingress.enabled }}
            "proxy_protocol_iRule": {
              "class": "iRule",
              "iRule": "when SERVER_CONNECTED {\n    TCP::respond \"PROXY TCP[IP::version] [IP::client_addr] [clientside {IP::local_addr}] [TCP::client_port] [clientside {TCP::local_port}]\\r\\n\"\n}"
            },
            "webdev_{{ .Values.cluster.name }}_ingress_443_vs": {
              "class": "Service_TCP",
              "iRules": [
                "proxy_protocol_iRule"
              ],
              "layer4": "tcp",
              "profileTCP": {
                "egress": {
                  "bigip": "/Common/tcp-lan-optimized-power"
                },
                "ingress": {
                  "bigip": "/Common/tcp-mobile-optimized-power"
                }
              },
              "snat": {
                "bigip": "{{ .Values.bigipCtrlAS3.snatPool }}"
              },
              "virtualPort": 443,
              "remark": "{{ .Values.cluster.name }} ingress vs",
              "virtualAddresses": [
                "{{ .Values.bigipCtrlAS3.ingress.vs.address }}"
              ],
              "pool": "{{ .Values.cluster.name }}_ingress_pool_30443"
            },
            "{{ .Values.cluster.name }}_ingress_pool_30443": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
                {
                  "servicePort": 30443,
                  "serverAddresses": {{ toJson .Values.bigipCtrlAS3.ingress.pool.members }}
                }
              ]
            },
            "webdev_{{ .Values.cluster.name }}_ingress_80_vs": {
              "class": "Service_TCP",
              "iRules": [
                "proxy_protocol_iRule"
              ],
              "layer4": "tcp",
              "profileTCP": {
                "egress": {
                  "bigip": "/Common/tcp-lan-optimized-power"
                },
                "ingress": {
                  "bigip": "/Common/tcp-mobile-optimized-power"
                }
              },
              "snat": {
                "bigip": "{{ .Values.bigipCtrlAS3.snatPool }}"
              },
              "virtualPort": 80,
              "remark": "{{ .Values.cluster.name }} ingress vs",
              "virtualAddresses": [
                "{{ .Values.bigipCtrlAS3.ingress.vs.address }}"
              ],
              "pool": "{{ .Values.cluster.name }}_ingress_pool_30080"
            },
            "{{ .Values.cluster.name }}_ingress_pool_30080": {
              "class": "Pool",
              "monitors": [
                "tcp"
              ],
              "members": [
                {
                  "servicePort": 30080,
                  "serverAddresses": {{ toJson .Values.bigipCtrlAS3.ingress.pool.members }}
                }
              ]
            {{- end }}
            }
          }
        }
      }
    }
{{- end }}
