{{- if .Values.bigipCtrlAS3.enabled }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: as3cm
  namespace: {{ $.Release.Namespace }}
  labels:
    f5type: virtual-server
    as3: "true"
data:
  template: |
    {
      "class": "AS3",
      "declaration": {
        "class": "ADC",
        "schemaVersion": "3.51.0",
        "label": "http",
        "remark": "{{ .Values.cluster.name }} Template",
        "{{ .Values.cluster.name }}": {
          "class": "Tenant",
          "as3": {
            "class": "Application",
            "template": "generic",
            "webdev_{{ .Values.cluster.name }}_kubeapi_{{ .Values.bigipCtrlAS3.vs.port }}_vs": {
              "class": "Service_L4",
              "layer4": "tcp",
              "profileL4": {
                "bigip": "/Common/fastL4"
              },
              "snat": {
                "bigip": "/Common/SNATPool"
              },
              "virtualPort": {{ .Values.bigipCtrlAS3.vs.port }},
              "remark": "{{ .Values.cluster.name }} kubeapi vs",
              "virtualAddresses": [
                "{{ .Values.bigipCtrlAS3.vs.address }}"
              ],
              "pool": "{{ .Values.cluster.name }}_kubeapi_pool"
            },
            "{{ .Values.cluster.name }}_kubeapi_pool": {
              "class": "Pool",
              "monitors": [
                {"bigip": "/Common/https_kubeapi_healthz"}
              ],
              "members": [
                {
                  "servicePort": {{ .Values.bigipCtrlAS3.pool.port }},
                  "serverAddresses": {{ toJson .Values.bigipCtrlAS3.pool.members }}
                }
              ]
            }
          }
        }
      }
    }
{{- end }}
