---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ $.Release.Namespace }}
stringData:
  password: {{ .Values.vsphereCluster.password }}
  username: {{ .Values.vsphereCluster.username }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: {{ $.Release.Namespace }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: vsphere-config-secret
      namespace: vmware-system-csi
    stringData:
      csi-vsphere.conf: |+
        [Global]
        thumbprint = ""
        {{- if .Values.vsphereCluster.insecure }}
        insecure-flag = true
        {{- end }}

        [VirtualCenter "{{ .Values.vsphereCluster.server }}"]
        user = "{{ .Values.vsphereCluster.username }}"
        password = "{{ .Values.vsphereCluster.password }}"
        datacenters = "{{ .Values.vsphereCluster.datacenter }}"

        [Network]
        public-network = "{{ .Values.vsphereCluster.publicNetwork }}"

    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-provider-vsphere-credentials
  namespace: {{ $.Release.Namespace }}
stringData:
  data: |
    apiVersion: v1
    kind: Secret
    metadata:
      labels:
        component: cloud-controller-manager
        vsphere-cpi-infra: secret
      name: cloud-provider-vsphere-credentials
      namespace: kube-system
    stringData:
      {{ .Values.vsphereCluster.server }}.password: {{ .Values.vsphereCluster.password }}
      {{ .Values.vsphereCluster.server }}.username: {{ .Values.vsphereCluster.username }}
    type: Opaque
type: addons.cluster.x-k8s.io/resource-set
