---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.vsphereCluster.controlPlaneEndpoint.host }}
    port: {{ .Values.vsphereCluster.controlPlaneEndpoint.port }}
  identityRef:
    kind: Secret
    name: {{ .Values.cluster.name }}
  server: {{ .Values.vsphereCluster.server }}
  thumbprint: "{{ .Values.vsphereCluster.thumbprint }}"
