apiVersion: v1
name: openldap
home: https://www.openldap.org
version: 1.3.0
appVersion: 2.4.48
description: DEPRECATED - Community developed LDAP software
icon: http://www.openldap.org/images/headers/LDAPworm.gif
keywords:
  - ldap
  - openldap
sources:
  - https://github.com/powerhome/helm-charts/charts/openldap
urls:
  - https://github.com/helm/charts/tree/master/stable/openldap
deprecated: false
engine: gotpl
