---
{{- if .Values.elasticsearch.credentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eck-resources.fullname" . }}-credentials
  labels:
{{ include "eck-resources.labels" . | indent 4 }}
type: Opaque
data:
  auth_username: {{ .Values.elasticsearch.credentials.username | b64enc | quote }}
  auth_password: {{ .Values.elasticsearch.credentials.password | b64enc | quote }}
{{- end }}

---
{{- if .Values.elasticsearch.secretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "eck-resources.fullname" . }}-keystore
  labels:
{{ include "eck-resources.labels" . | indent 4 }}
type: Opaque
data:
  {{- range $key,$value := .Values.elasticsearch.secretConfig }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
