dags:
  gitSync:
    enabled: true
    repo: "https://github.com/powerhome/nexus.git"
    branch: "main"
    rev: "HEAD"
    depth: 1
    subPath: "dags"
    credentialsSecret: "git-credentials"
  persistence:
    enabled: false

webserver:
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "4000m"

scheduler:
  replicas: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

workers:
  replicas: 2
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2000m"

redis:
  resources:
    requests:
      memory: "500Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

statsd:
  enabled: true
  resources:
    requests:
      memory: "100Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "100m"
